apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tzach112-hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tarrad/tsachos
    targetRevision: main
    path: Application/yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tzach112-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Ignore status differences for Route (OpenShift adds status automatically)
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status

